version: '3'
services:
  client:
    build:
      context: .
      target: client
    ports:
      - '5173:80'

  server:
    build:
      context: .
      target: server
    ports:
      - '6969:6969'
    volumes:
      - './packages/server/db-data:/app/db-data'
    command: 'node dist/index.js'
