DROP TABLE IF EXISTS Conversations;

CREATE TABLE Conversations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sub INTEGER NOT NULL,
  model TEXT NOT NULL,
  temperature INTEGER NOT NULL,
  max_tokens INTEGER NOT NULL,
  system_message TEXT NOT NULL,
  messages TEXT NOT NULL,
  title TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sub) REFERENCES Users (sub)
);
